"""Rebuild the factual NANPA lookup without third-party dependencies.

Download https://reports.nanpa.com/public/npa_report.csv, then run:
  python3 web/src/data/update-area-codes.py /path/to/npa_report.csv

Source index: https://www.nanpa.com/reports/npa-reports
US state names: https://pe.usps.com/text/pub28/28apb.htm
Only geographic codes currently marked in service are included. This is a
state/province/country index, not an area-code boundary or phone-location dataset.
"""

import csv
import hashlib
import io
import json
from collections import defaultdict
from datetime import datetime
from pathlib import Path
import sys

US_REGIONS = {
    "AL": "Alabama", "AK": "Alaska", "AS": "American Samoa",
    "AZ": "Arizona", "AR": "Arkansas", "CA": "California",
    "CO": "Colorado", "CT": "Connecticut", "DE": "Delaware",
    "DC": "District of Columbia", "FL": "Florida", "GA": "Georgia",
    "GU": "Guam", "HI": "Hawaii", "ID": "Idaho", "IL": "Illinois",
    "IN": "Indiana", "IA": "Iowa", "KS": "Kansas", "KY": "Kentucky",
    "LA": "Louisiana", "ME": "Maine", "MD": "Maryland",
    "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota",
    "MS": "Mississippi", "MO": "Missouri", "MT": "Montana",
    "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire",
    "NJ": "New Jersey", "NM": "New Mexico", "NY": "New York",
    "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio",
    "OK": "Oklahoma", "OR": "Oregon", "PA": "Pennsylvania",
    "PR": "Puerto Rico", "RI": "Rhode Island", "SC": "South Carolina",
    "SD": "South Dakota", "TN": "Tennessee", "TX": "Texas",
    "UT": "Utah", "VT": "Vermont", "VI": "U.S. Virgin Islands",
    "VA": "Virginia", "WA": "Washington", "WV": "West Virginia",
    "WI": "Wisconsin", "WY": "Wyoming", "CNMI": "Northern Mariana Islands",
}


def main():
    source = Path(sys.argv[1]).read_bytes()
    reader = csv.reader(io.StringIO(source.decode("utf-8-sig")))
    metadata = next(reader)
    if metadata[0] != "File Date":
        raise ValueError("Expected the NANPA CSV file-date row")
    fields = next(reader)
    groups = defaultdict(list)
    count = 0
    for values in reader:
        row = dict(zip(fields, values))
        if row["USE"] != "G" or row["IN_SERVICE"] != "Y":
            continue
        country, location = row["COUNTRY"], row["LOCATION"]
        if country == "US":
            region = US_REGIONS[location] + ", United States"
            query = region
        elif country == "CANADA":
            region = location.title() + ", Canada"
            # A code spanning provinces/territories cannot be represented by
            # one province. Keep the query broad and disclose full coverage.
            query = "Canada" if " -" in location else region
        else:
            region = location.title()
            query = region
        groups[(region, query)].append(row["NPA_ID"])
        count += 1

    lines = [
        "// Generated by update-area-codes.py; do not edit code assignments by hand.",
        "// Source: https://reports.nanpa.com/public/npa_report.csv",
        f"// NANPA file date: {metadata[1]}; {count} in-service geographic codes.",
        f"// Source CSV SHA-256: {hashlib.sha256(source).hexdigest()}",
        "// Geography is state/province/country level, not exact coverage.",
        f"export const nanpaFileDate = {json.dumps(datetime.strptime(metadata[1], '%m/%d/%Y').date().isoformat())};",
        "export const geographicAreaCodes: readonly (readonly [string, string, string])[] = [",
    ]
    for (region, query), codes in sorted(groups.items()):
        lines.append("  " + json.dumps([" ".join(codes), region, query], ensure_ascii=False) + ",")
    lines.append("];")
    Path(__file__).with_name("nanpaGeographic.ts").write_text("\n".join(lines) + "\n")
    print(f"Generated {count} geographic codes in {len(groups)} regions from {metadata[1]}.")


if __name__ == "__main__":
    main()
